module AppointmentsDoc
  extend Apipie::DSL::Concern

  # GET /appointments
  api :GET, '/appointments', 'List appointments of current user.'
  header :Authorization, 'Token generated by <strong>oauth_token</strong> prefixed by the word <strong>Bearer</strong>.
                          <br><strong>Example:</strong> Bearer dfoiaudsfasdfasd34p534spauasfd', required: true
  returns code: 200, desc: 'A successful response' do
    property :appointments, Array, desc: 'Array of appointment objects.' do
      property :appointment, Hash, desc: 'Appointment object.' do
        property :id, Integer, desc: 'Appointment ID.'
        property :scheduled_for, DateTime, desc: 'Date and Time for the appointment.'
        property :teacher_fullname, String, desc: 'Teacher fullname'
        property :course, String, desc: 'Course to learn.'
        property :status, Integer, desc: '0: Past appointments<br>1: Incoming appointments.'
      end
    end
  end
  error code: 401, desc: 'Header "Authorization" is missed.'
  error code: 403, desc: 'Header "Authorization" is not valid or expired.'
  def index
    # Something
  end

  # GET /appointments/last
  api :GET, '/appointments/last', 'Last appointment registered by the current user.'
  header :Authorization, 'Token generated by <strong>oauth_token</strong> prefixed by the word <strong>Bearer</strong>.
                          <br><strong>Example:</strong> Bearer dfoiaudsfasdfasd34p534spauasfd', required: true
  returns code: 200, desc: 'A successful response' do
    property :id, Integer, desc: 'Appointment ID.'
    property :user_id, Integer, desc: 'User ID which requests the appointment.'
    property :teacher_id, Integer, desc: 'Teacher ID which teaches.'
    property :scheduled_for, DateTime, desc: 'Date and Time for the appointment.'
  end
  error code: 401, desc: 'Header "Authorization" is missed.'
  error code: 403, desc: 'Header "Authorization" is not valid or expired.'
  def last
    # Something
  end

  # POST /appointments
  api :POST, '/appointments', 'Create an appointment for the current user.'
  header :Authorization, 'Token generated by <strong>oauth_token</strong> prefixed by the word <strong>Bearer</strong>.
                          <br><strong>Example:</strong> Bearer dfoiaudsfasdfasd34p534spauasfd', required: true
  param :appointment, Hash, required: true do
    param :teacher_id, Integer, desc: 'ID of the requested teacher.', required: true
    param :scheduled_for, String, desc: 'Date and time for the appointment.', required: true
  end
  returns code: 200, desc: 'A successful response' do
    property :appointment, Hash, desc: 'Appointment object.' do
      property :id, Integer, desc: 'Appointment ID.'
      property :scheduled_for, DateTime, desc: 'Date and Time for the appointment.'
      property :teacher_fullname, String, desc: 'Teacher fullname.'
      property :course, String, desc: 'Course to learn.'
      property :status, Integer, desc: '0: Past appointments<br>1: Incoming appointments.'
    end
  end
  error code: 401, desc: 'Header "Authorization" is missed.'
  error code: 403, desc: 'Header "Authorization" is not valid or expired.'
  error :unprocessable_entity, 'Could not save the entity.'
  def create
    # Something
  end

  # DELETE /appointments/1
  api :DELETE, '/appointments/:id', 'Destroy an appointment'
  header :Authorization, 'Token generated by <strong>oauth_token</strong> prefixed by the word <strong>Bearer</strong>.
                          <br><strong>Example:</strong> Bearer dfoiaudsfasdfasd34p534spauasfd', required: true
  param :id, :number, desc: 'ID of the appointment to destroy.', required: true
  returns code: 200, desc: 'A successful response' do
    property :id, Integer, desc: 'Appointment ID.'
    property :user_id, Integer, desc: 'User ID which requests the appointment.'
    property :teacher_id, Integer, desc: 'Teacher ID which teaches.'
    property :scheduled_for, DateTime, desc: 'Date and Time for the appointment.'
  end
  error code: 401, desc: 'Header "Authorization" is missed.'
  error code: 403, desc: 'Header "Authorization" is not valid or expired.'
  def destroy
    # Something
  end
end
