module CloudinaryDoc
  extend Apipie::DSL::Concern

  # GET /cloudinary
  api :GET, '/cloudinary', 'Show Cloudinary access keys.'
  header :Authorization, 'Token generated by <strong>oauth_token</strong> prefixed by the word <strong>Bearer</strong>.
                          <br><strong>Example:</strong> Bearer dfoiaudsfasdfasd34p534spauasfd', required: true
  returns code: 200, desc: 'A successful response' do
    property :cloud_name, String, desc: 'Cloudinary Cloud Name to upload images.'
    property :upload_preset, String, desc: 'Preset Key to upload images without Sign In Cloudinary Cloud.'
  end
  error code: 401, desc: 'Header "Authorization" is missed.'
  error code: 403, desc: 'Header "Authorization" is not valid or expired.'
  def index
    # Something here
  end
end
