# rubocop: disable Metrics/ModuleLength
module UsersDoc
  extend Apipie::DSL::Concern

  # POST /users
  api :POST, '/users', 'Create an user'
  param :user, Hash do
    param :username, String, desc: 'Username for login', required: true
    param :password, String, desc: 'Password for login', required: true
    param :email, String, desc: 'User email', required: true
    param :fullname, String, desc: 'User fullname', required: true
  end
  returns code: 200, desc: 'A successful response' do
    property :user, Hash, desc: 'Teachers object.' do
      property :id, Integer, desc: 'User ID.'
      property :fullname, String, desc: 'User fullname'
      property :username, String, desc: 'Username for login'
      property :email, String, desc: 'User email'
      property :admin, :boolean, desc: 'Is an admin?'
    end
  end
  error :unprocessable_entity, 'Could not save the entity.'
  def create
    # Something
  end

  # GET /users/myprofile
  api :GET, '/users/myprofile', 'Show the profile data of the current user.'
  header :Authorization, 'Token generated by <strong>oauth_token</strong> prefixed by the word <strong>Bearer</strong>.
                          <br><strong>Example:</strong> Bearer dfoiaudsfasdfasd34p534spauasfd', required: true
  returns code: 200, desc: 'A successful response' do
    property :myprofile, Hash, desc: 'Teachers object.' do
      property :id, Integer, desc: 'User ID.'
      property :fullname, String, desc: 'User fullname'
      property :username, String, desc: 'Username for login'
      property :email, String, desc: 'User email'
      property :admin, :boolean, desc: 'Is an admin?'
    end
  end
  error code: 401, desc: 'Header "Authorization" is missed.'
  error code: 403, desc: 'Header "Authorization" is not valid or expired.'
  def myprofile
    # Something
  end

  # GET /users
  api :GET, '/users', 'List users'
  header :Authorization, 'Token generated by <strong>oauth_token</strong> prefixed by the word <strong>Bearer</strong>.
                          <br><strong>Example:</strong> Bearer dfoiaudsfasdfasd34p534spauasfd', required: true
  returns code: 200, desc: 'A successful response' do
    property :users, Array, desc: 'Array of user objects.' do
      property :user, Hash, desc: 'User object.' do
        property :id, Integer, desc: 'User ID.'
        property :fullname, String, desc: 'User fullname'
        property :username, String, desc: 'Username for login'
        property :email, String, desc: 'User email'
        property :admin, :boolean, desc: 'Is an admin?'
      end
    end
  end
  error code: 401, desc: 'Header "Authorization" is missed.'
  error code: 403, desc: 'Header "Authorization" is not valid or expired.'
  def index
    # Something
  end

  # GET /users/1
  api :GET, '/users/:id', 'Show an user'
  header :Authorization, 'Token generated by <strong>oauth_token</strong> prefixed by the word <strong>Bearer</strong>.
                          <br><strong>Example:</strong> Bearer dfoiaudsfasdfasd34p534spauasfd', required: true
  param :id, Integer, desc: 'User ID to show.', required: true
  returns code: 200, desc: 'A successful response' do
    property :user, Hash, desc: 'User object.' do
      property :id, Integer, desc: 'User ID.'
      property :fullname, String, desc: 'User fullname'
      property :username, String, desc: 'Username for login'
      property :email, String, desc: 'User email'
      property :admin, :boolean, desc: 'Is an admin?'
    end
  end
  error code: 401, desc: 'Header "Authorization" is missed.'
  error code: 403, desc: 'Header "Authorization" is not valid or expired.'
  def show
    # Something
  end

  # GET /users/last
  api :GET, '/users/last', 'Show the last registered user'
  header :Authorization, 'Token generated by <strong>oauth_token</strong> prefixed by the word <strong>Bearer</strong>.
                          <br><strong>Example:</strong> Bearer dfoiaudsfasdfasd34p534spauasfd', required: true
  returns code: 200, desc: 'A successful response' do
    property :user, Hash, desc: 'User object.' do
      property :id, Integer, desc: 'User ID.'
      property :fullname, String, desc: 'User fullname'
      property :username, String, desc: 'Username for login'
      property :email, String, desc: 'User email'
      property :admin, :boolean, desc: 'Is an admin?'
    end
  end
  error code: 401, desc: 'Header "Authorization" is missed.'
  error code: 403, desc: 'Header "Authorization" is not valid or expired.'
  def last
    # Something
  end

  # PATCH/PUT /users/1
  api :PATCH, '/users/:id', 'Update an user'
  api :PUT, '/users/:id', 'Update an user'
  header :Authorization, 'Token generated by <strong>oauth_token</strong> prefixed by the word <strong>Bearer</strong>.
                          <br><strong>Example:</strong> Bearer dfoiaudsfasdfasd34p534spauasfd', required: true
  param :id, Integer, desc: 'User ID to update.', required: true
  param :user, Hash, required: true do
    param :fullname, String, desc: 'User fullname', required: false
    param :username, String, desc: 'Username for login', required: false
    param :email, String, desc: 'User email', required: false
    param :password, String, desc: 'User password', required: false
    param :admin, :boolean, desc: 'Is an admin?', required: false
  end
  returns code: 200, desc: 'A successful response with the updated user.' do
    property :user, Hash, desc: 'User object.' do
      property :id, Integer, desc: 'User ID.'
      property :fullname, String, desc: 'User fullname'
      property :username, String, desc: 'Username for login'
      property :email, String, desc: 'User email'
      property :admin, :boolean, desc: 'Is an admin?'
    end
  end
  error code: 401, desc: 'Header "Authorization" is missed.'
  error code: 403, desc: 'Header "Authorization" is not valid or expired.'
  error :unprocessable_entity, 'Could not save the entity.'
  def update
    # Something
  end

  # DELETE /users/1
  api :DELETE, '/users/:id', 'Destroy an user'
  header :Authorization, 'Token generated by <strong>oauth_token</strong> prefixed by the word <strong>Bearer</strong>.
                          <br><strong>Example:</strong> Bearer dfoiaudsfasdfasd34p534spauasfd', required: true
  param :id, Integer, desc: 'User ID to destroy.', required: true
  returns code: 200, desc: 'A successful response, with information of the destroyed user.' do
    property :user, Hash, desc: 'User object.' do
      property :id, Integer, desc: 'User ID.'
      property :fullname, String, desc: 'User fullname'
      property :username, String, desc: 'Username for login'
      property :email, String, desc: 'User email'
      property :admin, :boolean, desc: 'Is an admin?'
    end
  end
  error code: 401, desc: 'Header "Authorization" is missed.'
  error code: 403, desc: 'Header "Authorization" is not valid or expired.'
  def destroy
    # Something
  end
end
# rubocop: enable Metrics/ModuleLength
