class Api::V1::AppointmentsController < ApplicationController
  before_action :doorkeeper_authorize!
  before_action :set_appointment, only: %i[destroy]
  before_action :set_current_user, only: %i[index create last]
  before_action :set_last_appointment, only: %i[last]

  # GET /appointments
  api :GET, '/appointments', 'List appointments of current user.'
  header :Authorization, 'Token generated by <strong>oauth_token</strong> prefixed by the word <strong>Bearer</strong>.
                          <br><strong>Example:</strong> Bearer dfoiaudsfasdfasd34p534spauasfd', required: true
  returns code: 200, desc: 'A successful response' do
    property :appointments, Array, desc: 'Array of appointment objects.' do
      property :appointment, Hash, desc: 'Appointment object.' do
        property :id, Integer, desc: 'Appointment ID.'
        property :scheduled_for, DateTime, desc: 'Date and Time for the appointment.'
        property :teacher_fullname, String, desc: 'Teacher fullname'
        property :course, String, desc: 'Course to learn.'
        property :status, Integer, desc: '0: Past appointments<br>1: Incoming appointments.'
      end
    end
  end
  error code: 401, desc: 'Header "Authorization" is missed.'
  error code: 403, desc: 'Header "Authorization" is not valid or expired.'
  def index
    if @current_user
      @appointments = Appointment
        .select(:id,
                :scheduled_for,
                'teachers.fullname as teacher_fullname',
                'teachers.course',
                'CASE WHEN scheduled_for > timezone(\'utc\', now()) THEN 1 ELSE 0 END as status')
        .joins(:teacher)
        .where(user_id: @current_user.id)
        .order(scheduled_for: :asc)

      render :index
    else
      render json: return_error_message(403), status: :forbidden
    end
  end

  # GET /appointments/last
  api :GET, '/appointments/last', 'Last appointment registered by the current user.'
  header :Authorization, 'Token generated by <strong>oauth_token</strong> prefixed by the word <strong>Bearer</strong>.
                          <br><strong>Example:</strong> Bearer dfoiaudsfasdfasd34p534spauasfd', required: true
  returns code: 200, desc: 'A successful response' do
    property :id, Integer, desc: 'Appointment ID.'
    property :user_id, Integer, desc: 'User ID which requests the appointment.'
    property :teacher_id, Integer, desc: 'Teacher ID which teaches.'
    property :scheduled_for, DateTime, desc: 'Date and Time for the appointment.'
  end
  error code: 401, desc: 'Header "Authorization" is missed.'
  error code: 403, desc: 'Header "Authorization" is not valid or expired.'
  def last
    render :show
  end

  # POST /appointments
  api :POST, '/appointments', 'Create an appointment for the current user.'
  header :Authorization, 'Token generated by <strong>oauth_token</strong> prefixed by the word <strong>Bearer</strong>.
                          <br><strong>Example:</strong> Bearer dfoiaudsfasdfasd34p534spauasfd', required: true
  param :appointment, Hash, required: true do
    param :teacher_id, Integer, desc: 'ID of the requested teacher.', required: true
    param :scheduled_for, String, desc: 'Date and time for the appointment.', required: true
  end
  returns code: 200, desc: 'A successful response' do
    property :appointment, Hash, desc: 'Appointment object.' do
      property :id, Integer, desc: 'Appointment ID.'
      property :scheduled_for, DateTime, desc: 'Date and Time for the appointment.'
      property :teacher_fullname, String, desc: 'Teacher fullname.'
      property :course, String, desc: 'Course to learn.'
      property :status, Integer, desc: '0: Past appointments<br>1: Incoming appointments.'
    end
  end
  error code: 401, desc: 'Header "Authorization" is missed.'
  error code: 403, desc: 'Header "Authorization" is not valid or expired.'
  def create
    @new_appointment = Appointment.new(appointment_params)
    @new_appointment.user_id = @current_user.id

    if @new_appointment.scheduled_for > Time.now.utc
      if @new_appointment.save
        @appointment = Appointment
          .select(:id,
                  :scheduled_for,
                  'teachers.fullname as teacher_fullname',
                  'teachers.course',
                  'CASE WHEN scheduled_for > timezone(\'utc\', now()) THEN 1 ELSE 0 END as status')
          .joins(:teacher)
          .where(id: @new_appointment.id)
          .first

        render json: { 'appointment' => @appointment }, status: :created
      else
        render json: @new_appointment.errors, status: :unprocessable_entity
      end
    else
      render json: return_error_message(403), status: :forbidden
    end
  end

  # DELETE /appointments/1
  api :DELETE, '/appointments/:id', 'Destroy an appointment'
  header :Authorization, 'Token generated by <strong>oauth_token</strong> prefixed by the word <strong>Bearer</strong>.
                          <br><strong>Example:</strong> Bearer dfoiaudsfasdfasd34p534spauasfd', required: true
  param :id, :number, desc: 'ID of the appointment to destroy.', required: true
  returns code: 200, desc: 'A successful response' do
    property :id, Integer, desc: 'Appointment ID.'
    property :user_id, Integer, desc: 'User ID which requests the appointment.'
    property :teacher_id, Integer, desc: 'Teacher ID which teaches.'
    property :scheduled_for, DateTime, desc: 'Date and Time for the appointment.'
  end
  error code: 401, desc: 'Header "Authorization" is missed.'
  error code: 403, desc: 'Header "Authorization" is not valid or expired.'
  def destroy
    if admin_permission? || @appointment.user_id == current_user.id
      @appointment.destroy
      render :show
    else
      render json: return_error_message(403), status: :forbidden
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_last_appointment
    @appointment = Appointment.where(user_id: @current_user.id).last
  end

  def set_appointment
    @appointment = Appointment.find(params[:id])
  end

  def set_current_user
    @current_user = current_user
  end

  # Only allow a list of trusted parameters through.
  def appointment_params
    params.require(:appointment).permit(:scheduled_for, :teacher_id)
  end
end
