# rubocop: disable Metrics/ClassLength
class Api::V1::UsersController < ApplicationController
  before_action :doorkeeper_authorize!, except: %i[create]
  before_action :set_user, only: %i[show update destroy]
  before_action :set_users, only: %i[index]
  before_action :set_last_user, only: %i[last]

  # POST /users
  api :POST, '/users', 'Create an user'
  param :user, Hash do
    param :username, String, desc: 'Username for login', required: true
    param :password, String, desc: 'Password for login', required: true
    param :email, String, desc: 'User email', required: true
    param :fullname, String, desc: 'User fullname', required: true
  end
  returns code: 200, desc: 'A successful response' do
    property :user, Hash, desc: 'Teachers object.' do
      property :id, Integer, desc: 'User ID.'
      property :fullname, String, desc: 'User fullname'
      property :username, String, desc: 'Username for login'
      property :email, String, desc: 'User email'
      property :admin, :boolean, desc: 'Is an admin?'
    end
  end
  error :unprocessable_entity, 'Could not save the entity.'
  def create
    @user = User.new(user_params)

    if @user.save
      render :show, status: :created
    else
      render json: @user.errors, status: :unprocessable_entity
    end
  end

  # GET /users/myprofile
  api :GET, '/users/myprofile', 'Show the profile data of the current user.'
  header :Authorization, 'Token generated by <strong>oauth_token</strong> prefixed by the word <strong>Bearer</strong>.
                          <br><strong>Example:</strong> Bearer dfoiaudsfasdfasd34p534spauasfd', required: true
  returns code: 200, desc: 'A successful response' do
    property :myprofile, Hash, desc: 'Teachers object.' do
      property :id, Integer, desc: 'User ID.'
      property :fullname, String, desc: 'User fullname'
      property :username, String, desc: 'Username for login'
      property :email, String, desc: 'User email'
      property :admin, :boolean, desc: 'Is an admin?'
    end
  end
  error code: 401, desc: 'Header "Authorization" is missed.'
  error code: 403, desc: 'Header "Authorization" is not valid or expired.'
  def myprofile
    render :myprofile
  end

  # GET /users
  api :GET, '/users', 'List users'
  header :Authorization, 'Token generated by <strong>oauth_token</strong> prefixed by the word <strong>Bearer</strong>.
                          <br><strong>Example:</strong> Bearer dfoiaudsfasdfasd34p534spauasfd', required: true
  returns code: 200, desc: 'A successful response' do
    property :users, Array, desc: 'Array of user objects.' do
      property :user, Hash, desc: 'User object.' do
        property :id, Integer, desc: 'User ID.'
        property :fullname, String, desc: 'User fullname'
        property :username, String, desc: 'Username for login'
        property :email, String, desc: 'User email'
        property :admin, :boolean, desc: 'Is an admin?'
      end
    end
  end
  error code: 401, desc: 'Header "Authorization" is missed.'
  error code: 403, desc: 'Header "Authorization" is not valid or expired.'
  def index
    if admin_permission?
      render :index
    else
      render json: return_error_message(403), status: :forbidden
    end
  end

  # GET /users/1
  api :GET, '/users/:id', 'Show an user'
  header :Authorization, 'Token generated by <strong>oauth_token</strong> prefixed by the word <strong>Bearer</strong>.
                          <br><strong>Example:</strong> Bearer dfoiaudsfasdfasd34p534spauasfd', required: true
  param :id, Integer, desc: 'User ID to show.', required: true
  returns code: 200, desc: 'A successful response' do
    property :user, Hash, desc: 'User object.' do
      property :id, Integer, desc: 'User ID.'
      property :fullname, String, desc: 'User fullname'
      property :username, String, desc: 'Username for login'
      property :email, String, desc: 'User email'
      property :admin, :boolean, desc: 'Is an admin?'
    end
  end
  error code: 401, desc: 'Header "Authorization" is missed.'
  error code: 403, desc: 'Header "Authorization" is not valid or expired.'
  def show
    if admin_permission?
      render :show
    else
      render json: return_error_message(403), status: :forbidden
    end
  end

  # GET /users/last
  api :GET, '/users/last', 'Show the last registered user'
  header :Authorization, 'Token generated by <strong>oauth_token</strong> prefixed by the word <strong>Bearer</strong>.
                          <br><strong>Example:</strong> Bearer dfoiaudsfasdfasd34p534spauasfd', required: true
  returns code: 200, desc: 'A successful response' do
    property :user, Hash, desc: 'User object.' do
      property :id, Integer, desc: 'User ID.'
      property :fullname, String, desc: 'User fullname'
      property :username, String, desc: 'Username for login'
      property :email, String, desc: 'User email'
      property :admin, :boolean, desc: 'Is an admin?'
    end
  end
  error code: 401, desc: 'Header "Authorization" is missed.'
  error code: 403, desc: 'Header "Authorization" is not valid or expired.'
  def last
    if admin_permission?
      render :show
    else
      render json: return_error_message(403), status: :forbidden
    end
  end

  # PATCH/PUT /users/1
  api :PATCH, '/users/:id', 'Update an user'
  api :PUT, '/users/:id', 'Update an user'
  header :Authorization, 'Token generated by <strong>oauth_token</strong> prefixed by the word <strong>Bearer</strong>.
                          <br><strong>Example:</strong> Bearer dfoiaudsfasdfasd34p534spauasfd', required: true
  param :id, Integer, desc: 'User ID to update.', required: true
  param :user, Hash, required: true do
    param :fullname, String, desc: 'User fullname', required: false
    param :username, String, desc: 'Username for login', required: false
    param :email, String, desc: 'User email', required: false
    param :password, String, desc: 'User password', required: false
    param :admin, :boolean, desc: 'Is an admin?', required: false
  end
  returns code: 200, desc: 'A successful response with the updated user.' do
    property :user, Hash, desc: 'User object.' do
      property :id, Integer, desc: 'User ID.'
      property :fullname, String, desc: 'User fullname'
      property :username, String, desc: 'Username for login'
      property :email, String, desc: 'User email'
      property :admin, :boolean, desc: 'Is an admin?'
    end
  end
  error code: 401, desc: 'Header "Authorization" is missed.'
  error code: 403, desc: 'Header "Authorization" is not valid or expired.'
  error :unprocessable_entity, 'Could not save the entity.'
  def update
    if admin_permission?
      if @user.update(user_params)
        render :show
      else
        render json: @user.errors, status: :unprocessable_entity
      end
    else
      render json: return_error_message(403), status: :forbidden
    end
  end

  # DELETE /users/1
  api :DELETE, '/users/:id', 'Destroy an user'
  header :Authorization, 'Token generated by <strong>oauth_token</strong> prefixed by the word <strong>Bearer</strong>.
                          <br><strong>Example:</strong> Bearer dfoiaudsfasdfasd34p534spauasfd', required: true
  param :id, Integer, desc: 'User ID to destroy.', required: true
  returns code: 200, desc: 'A successful response, with information of the destroyed user.' do
    property :user, Hash, desc: 'User object.' do
      property :id, Integer, desc: 'User ID.'
      property :fullname, String, desc: 'User fullname'
      property :username, String, desc: 'Username for login'
      property :email, String, desc: 'User email'
      property :admin, :boolean, desc: 'Is an admin?'
    end
  end
  error code: 401, desc: 'Header "Authorization" is missed.'
  error code: 403, desc: 'Header "Authorization" is not valid or expired.'
  def destroy
    if admin_permission?
      Appointment.where(user_id: @user.id).destroy_all
      @user.destroy

      render :show
    else
      render json: return_error_message(403), status: :forbidden
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_last_user
    @user = User.last
  end

  def set_user
    @user = User.find(params[:id])
  end

  def set_users
    @users = User.all.order(:fullname)
  end

  # Only allow a list of trusted parameters through.
  def user_params
    params.require(:user).permit(:fullname, :email, :username, :password)
  end
end
# rubocop: enable Metrics/ClassLength
